export const images = {
    logo: require('../../assets/app_logo.png'),
    bride: require('../../assets/bride.png'),
    baker: require('../../assets/baker.png'),
    baker_bg: require('../../assets/baker_bg.png'),
    bride_bg: require('../../assets/bride_bg.png'),
    cake: require('../../assets/bg_cake.png'),
    cake1: require('../../assets/bg_welcome_bride.png'),
    cake2: require('../../assets/icon.png'),
    icon1: require('../../assets/visit.png'),
    icon2: require('../../assets/activity.png'),
    icon3: require('../../assets/performance.png'),
    icon4: require('../../assets/tour.png'),
    forgot: require('../../assets/forgot.png'),
bg_welcome_vip:require('../../assets/bg_welcome_vip.png'),
    iconlast: require('../../assets/iconlast.png'),
    iconimage: require('../../assets/iconimage.jpg'),
uploadcake: require('../../assets/uploadcake.png'),
    avatarbride: require('../../assets/avatarbride.png'),
    map: require('../../assets/map.jpg'),
    directory: require('../../assets/directory.png'),
    pinned: require('../../assets/pinned.png'),
    social: require('../../assets/social.png'),
    noimage: require('../../assets/noimage.png'),
    face: require('../../assets/face.jpg'),
    y1: require('../../assets/y1.jpg'),
    y2: require('../../assets/y2.jpg'),
    y3: require('../../assets/y3.jpg'),
    splash: require('../../assets/patanjali.png'),
    ramdev: require('../../assets/ramdev.jpg'),
    bal: require('../../assets/bal.jpg'),
    blue: require('../../assets/blue.jpg'),
    patanjali_banner: require('../../assets/patanjali_banner.jpg'),
    patanjali_banner_1: require('../../assets/patanjali_banner_1.jpg'),

};